DROP TABLE IF EXISTS RSSCHANNELFEED;
CREATE TABLE RSSCHANNELFEED
(
    FEED_ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    COPYRIGHT      VARCHAR(50),
    LASTBUILDDATE  VARCHAR(50),
    LINK           VARCHAR(15),
    DESCRIPTION    VARCHAR(50),
    GENERATOR      VARCHAR(50),
    TITLE          VARCHAR(50),
    PUBLISHED_DATE VARCHAR(50),
    TTL            INT
);

DROP TABLE IF EXISTS RSSCHANNELITEM;
CREATE TABLE RSSCHANNELITEM
(
    LINK           VARCHAR(15),
    DESCRIPTION    VARCHAR(50),
    TITLE          VARCHAR(50),
    PUBLISHED_DATE VARCHAR(50),
    GUID_CONTENT   VARCHAR(30),
    FEED_ID        BIGINT,
    FOREIGN KEY (FEED_ID) REFERENCES RSSCHANNELFEED (FEED_ID)
);
