DROP TABLE IF EXISTS RSSCHANNELFEED;
CREATE TABLE RSSCHANNELFEED
(
    FEED_ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    COPYRIGHT      VARCHAR(100),
    LASTBUILDDATE  VARCHAR(50),
    LINK           VARCHAR(50),
    DESCRIPTION    VARCHAR(150),
    GENERATOR      VARCHAR(50),
    TITLE          VARCHAR(50),
    PUBLISHED_DATE VARCHAR(50),
    TTL            INT
);

DROP TABLE IF EXISTS RSSCHANNELITEM;
CREATE TABLE RSSCHANNELITEM
(
    LINK           VARCHAR(50),
    DESCRIPTION    VARCHAR(150),
    TITLE          VARCHAR(50),
    PUBLISHED_DATE VARCHAR(50),
    GUID_CONTENT   VARCHAR(50),
    FEED_ID        BIGINT AUTO_INCREMENT,
);
